# Generated by Django 4.1.4 on 2022-12-31 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='publicer',
        ),
        migrations.AddField(
            model_name='paper',
            name='publicer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
